// src/App.tsx
import React, { useEffect, useState } from 'react';
import { Theme } from './themes';
import Title from './components/Title';
import './App.css';

const repos = [
	'UserLogin',
	'Dankcord',
	'Ascii Converter',
	'Undertale Dialogues',
];

const App: React.FC = () => {
	const [theme, setTheme] = useState(
		(localStorage.getItem('theme') ?? 'windows') as Theme
	);

	const switchTheme = () => {
		setTheme(prev => (prev === 'windows' ? 'linux' : 'windows'));
	};

	useEffect(() => {
		localStorage.setItem('theme', theme);
		document.body.classList.toggle('linux-theme', theme === 'linux');
	}, [theme]);

	const birthday = new Date();
	birthday.setMonth(7);
	birthday.setDate(31);

	const now = new Date();
	let age = now.getFullYear() - 2006;
	if (now < birthday) age--;

	return (
		<>
			<div id="switch" onClick={switchTheme}>
				<div
					style={{ float: theme === 'windows' ? 'left' : 'right' }}
					id="switch-thumb"></div>
			</div>
			<Title theme={theme} />

			<p id="main-text">
				I'm some {age}-year old who likes coding. <em>A lot</em>, actually.
				Full-stack web developer too (sort of), using primarily the MERN stack.
				Of course, I have done other kinds of projects before apart from web
				dev, such as Discord bots and Minecraft plugins. Also, anime
			</p>

			<br />
			<p>Also, anime enthusiast and Minecraft fan.</p>

			<h3>Some of my projects:</h3>
			<ul id="repos-list">
				{repos.map(repo => (
					<li key={repo}>
						<a
							href={`https://github.com/ElCholoGamer/${repo
								.toLowerCase()
								.replace(/ /g, '-')}`}>
							{repo}
						</a>
					</li>
				))}
			</ul>

			<p id="social">
				Follow me on <a href="https://github.com/ElCholoGamer">GitHub</a>!
			</p>
		</>
	);
};

export default App;

// src/App.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	import ScrollText from './components/ScrollText.svelte';
	import CommandPrefix from './components/CommandPrefix.svelte';
	import { getAge } from './utils';
	import { Theme } from './constants';

	const age = getAge(new Date(2006, 7, 31));

	const repos = [
		{ path: 'userlogin', label: 'UserLogin' },
		{ path: 'dankcord', label: 'Dankcord' },
		{ path: 'ascii-converter', label: 'Ascii Converter' },
		{ path: 'undertale-dialogues', label: 'Undertale Dialogues' },
	];

	let theme = Theme.WINDOWS;

	onMount(() => {
		const storedTheme = localStorage.getItem('theme');
		if (Object.values(Theme).includes(storedTheme as any)) {
			theme = storedTheme as Theme;
		}
	});

	function switchTheme() {
		theme = theme === Theme.WINDOWS ? Theme.LINUX : Theme.WINDOWS;
		localStorage.setItem('theme', theme);
	}

	$: document.body.classList.toggle('linux-theme', theme === Theme.LINUX);
</script>

<main>
	<div id="switch" on:click="{switchTheme}">
		<div
			style="{`float: ${theme === Theme.WINDOWS ? 'left' : 'right'}`}"
			id="switch-thumb"
		></div>
	</div>

	<h2 id="title">
		<CommandPrefix theme="{theme}" /><ScrollText
			text="echo &quot;Hello, world!&quot;"
			theme="{theme}"
		/>
	</h2>

	<p id="main-text">
		I'm some {age}-year old who likes coding. <em>A lot</em>, actually.
		Full-stack web developer too (sort of), using primarily the MERN stack. Of
		course, I have done other kinds of projects before apart from web dev, such
		as Discord bots and Minecraft plugins.
	</p>

	<br />
	<p>Also, anime enthusiast and Minecraft fan.</p>

	<h3>Some of my projects:</h3>
	<ul id="repos-list">
		{#each repos as repo}
			<li>
				<a href="{`https://github.com/ElCholoGamer/${repo.path}`}">
					{repo.label}
				</a>
			</li>
		{/each}
	</ul>

	<p id="social">
		Follow me on <a href="https://github.com/ElCholoGamer">GitHub</a>!
	</p>
</main>
